pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                 stage("checkout") {
                    steps {
                        checkout scm
                    }
                }
                stage('Instalar dependencias') {
                    steps {
                        sh 'npm install'
                    }
                }
                stage('Ejecutar test') {
                    steps {
                        sh 'npm run test'
                    }
                }
                stage('Hacer build') {
                    steps {
                        sh 'npm run build'
                    }
                }
            }
        }
    }
}
